# Generated by Django 4.2.8 on 2023-12-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="description",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(
                default="./static/default.png", upload_to="uploads/"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=150),
        ),
    ]
